<?php

define('USER_CREATED_SUCCESSFULLY', 0);
define('USER_CREATE_FAILED', 1);
define('USER_EMAIL_ALREADY_EXISTS', 2);
define('USER_USERNAME_ALREADY_EXISTS', 3);
define('USER_CREATED_EMAIL_SENT', 13);
define('USER_CREATED_EMAIL_NOT_SENT', 14);
define('USER_CREATED_AND_UPDATE_FAILED', 27);

define('USER_IS_NOW_VERIFIED', 5);
define('VERIFICATION_CODE_DOES_NOT_EXIST', 7);
define('USER_VERIFY_FAILED', 8);
define('USER_NEEDS_TO_BE_VERIFIED', 16);
define('USER_ALREADY_VERIFIED', 9);

define('LOGIN_SUCCESS', 12);
define('PASSWORD_INCORRECT', 10);
define('EMAIL_DOES_NOT_EXIST', 11);

define('EMAIL_SENT', 17);
define('EMAIL_NOT_SENT', 18);

define('FAILED_AUTHENTICATION', 19);
define('ERROR_UPLOADING_IMAGE', 20);

define('IMG_UPLOADED_UPDATE_SUCCESS', 21);
define('IMG_UPLOADED_UPDATE_FAILED', 22);

define('ERROR_EXECUTING_QUERY', 23);
define('SUCCESS_EXECUTING_QUERY', 24);

define('USER_EMAIL_ALREADY_EXISTS_AND_ACTIVATED', 25);
define('USER_EMAIL_ALREADY_EXISTS_AND_NOT_ACTIVATED', 26);

define('ERROR_BAD_DATE_TIME_FORMAT', 28);

?>